services:
  - type: web
    name: us30ea-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/ui/app.py --server.port $PORT --server.headless true
    plan: free
